### ISSUE TITLE
Roadmap for sanity-ruby gem

### ISSUE THREAD

**Issue by olivertedwards** [dvmonroe/sanity-ruby#27]
Great initiative on creating a Ruby gem for Sanity :)

I am researching which content platform to build a fairly large project with—wondering if you guys have any thoughts about the direction of this gem or some kind of roadmap?

Would be very helpful to know a little more!

Have a great week, best Oliver

**Comment by dvmonroe** [comment]
@olivertedwards apologies for the delay. There's no current roadmap for this gem. This gem was built to help our team manage interactions between Rails apps and our Sanity desk. TMK most available features available through Sanity's API are supported via this gem.

Are there features here that are missing or that you'd like to see us work on? Always open to suggestions

**Comment by dvmonroe** [comment]
Closing for now.
