### ISSUE TITLE
undefined method serializer and auto_serialize

### ISSUE THREAD

**Issue by sappony-org** [dvmonroe/sanity-ruby#28]
Hello, I'm trying to use your gem with my RoR 7 app and I'm following the docs, however, I'm getting an error when I add serialization per your example. This is for both auto_serialize and a custom serializer. I imagine I'm missing something small. The rest of the documentation works.

For example:

```
class Post < Sanity::Resource
  auto_serialize
  
  mutatable only: %i(create delete)
  queryable
end
```

**Comment by dvmonroe** [comment]
@sappony-org If you were following the docs and using v0.2.0 (the last release before now) the issue was that our docs were ahead of released versions. My apologies. 

I've cut v0.3.0. Might try to bundle update and re-test your usage. If you continue to have issues please do post error logs.
