### ISSUE TITLE
Add support for multiple clients

### ISSUE THREAD

**Issue by conrad** [dvmonroe/sanity-ruby#30]
It would be very useful to be able to instantiate multiple clients and have them be able to use different settings and tokens. 

That way you could have different processes with different permissions. Maybe you just want one background to job to have write permission. 

Apps would also be able either to interact with multiple datasets, perspectives, or projects. Or you could be able to switch between projects on the server just for one user without switching the dataset for every other user. That way people could build apps easily with an edit & preview mode while still serving traffic to others of just published production data.

**Comment by dvmonroe** [comment]
Hey @conrad thanks for the note! 

There's nothing inherently stopping you in this gem from instantiating multiple clients.

```ruby
Sanity.configure do |s|
  s.token = "123"
  s.api_version = "v2021-03-25"
  s.project_id = "project1"
  s.dataset = "development"
  s.use_cdn = false
end

# This document gets created in "project1"
Sanity::Document.create(params: {_type: "user", first_name: "Carl", last_name: "Sagan"})

# configure Sanity for project2
Sanity.configuration.project_id = "project2"
# This document gets created in "project2"
Sanity::Document.create(params: {_type: "user", first_name: "Carl", last_name: "Sagan"})

```

The biggest problem with the above code is that it's **not thread-safe**. 

Are you looking for a **thread safe** implementation? If yes, indeed we would need to make an update to support thread-local configuration.
