### ISSUE TITLE
Thread safe configuration is difficult to use in multi-threaded systems (Rails)

### ISSUE THREAD

**Issue by cyu** [dvmonroe/sanity-ruby#36]
The recent changes where the configuration is stored in a thread local makes it cumbersome to use in Rails.  Traditionally, the expectation would be that the `configure` be setup in a Rails initializer, but that configuration doesn't get carried over into the Rails handler threads.  The designed approach would dictate that we configure the gem every time  before handling requests (like in a `before_action` of the `ApplicationController`), even if we don't need a Sanity connection.  Fortunately, the environment variable approach still works, but is not my preference.

I understand that Rails is not the only place this gem is used, but it seems like having a global configuration would be a more common need.

Here are to suggestions to accommodate both scenarios:

**Option 1:** Global configuration is the default, thread local is optional.  Default `configure` goes back to the previous non-Thread local implementation, but add away to override the global configuration with a thread local one:

```ruby
# Configuration is stored in ThreadLocal, overrides global configuration
Sanity.configure :thread do |s|
  s.token = "..."
  s.project_id = "..."
  s.dataset = "..."
  s.use_cdn = false
end

# Clear ThreadLocal configuration, falling back to global
Sanity.reset_configuration :thread

# Bonus: run custom configuration in a block
def sanity_around_action
  Sanity.with_configuration(configuration) do
    # uses new thread local configuration
    yield
  end
  # switches back to previous thread local or global configuration
end
```

**Option 2:** Keep ThreadLocal configuration the default, allow global configuration
```ruby
# Set global configuration
Sanity.configure :global do |s|
  s.token = "..."
  s.project_id = "..."
  s.dataset = "..."
  s.use_cdn = false
end

# reset_configuration and with_configuration methods would still apply like in Option 1
```

My preference is Option 1, but Option 2 is backwards compatible.

**Comment by dvmonroe** [comment]
@cyu thanks for the writeup. Appreciate the thoughts and I get what you're saying. 


> Fortunately, the environment variable approach still works

This was certainly the thought specific to a Rails environment.

.....
Going off your suggestions and in keeping this simple, let's add another config var `use_global_config` and update the self.configuration method to support this in a backwards compatible way. Would that help you?

```ruby

def initialize
    # Setting to false for backwards compatibility 
    #
    # Set to true in a Rails env if working with a single Sanity project/not interacting with multiple databases/projects
    # for traditional/expected Rails setup with an initializer
    @use_global_config = false
end

....
  
def self.configuration
  if config.use_global_config
    @global_configuration ||= Configuration.new
  else
    Thread.current[:sanity_configuration] ||= Configuration.new
  end
end
  
....
  
def self.configuration=(config)
  if config.use_global_config
    @global_configuration = config
  else
    Thread.current[:sanity_configuration] = config
  end
end
```
